theme: just-the-docs
color_scheme: dark

include: [".well-known"]

title: HouseCurve
description: Simple audio system tuning
repository: housecurve/housecurve.github.io

logo: /assets/img/title_icon.png
google_analytics: G-CLP8SY1HP1

search_enabled: true
heading_level: 2

heading_anchors: true
footer_content: "Copyright &copy; 2022 Greg Wilding - Made in Canada - info@housecurve.com"
gh_edit_links: false
