theme: just-the-docs
color_scheme: dark

include: [".well-known"]

title: HouseCurve
description: Simple audio system tuning
repository: housecurve/housecurve.github.io
logo: /assets/img/small.png
google_analytics: G-CLP8SY1HP1

footer_content: "Copyright &copy; 2022 Greg Wilding"
