remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

include: [".well-known"]

title: HouseCurve
description: Simple audio system tuning
logo: /assets/img/small.png
google_analytics: G-CLP8SY1HP1

kramdown:
   toc_levels: 2..3

