remote_theme: just-the-docs/just-the-docs
color_scheme: dark

include: [".well-known"]

title: HouseCurve
tagline: Simple Audio System Tuning
description: HouseCurve is an iOS app for tuning audio systems.  Use it for room correction, adjusting equalizers, setting subwoofer phase, choosing crossover frequencies and more.
logo: /assets/img/title_icon.png

appstore: https://apps.apple.com/ca/app/housecurve/id1470695018
ga_tracking: G-CLP8SY1HP1

search_enabled: true
heading_level: 2

heading_anchors: true
gh_edit_links: false


features:
- title: Objective
  description: See how it sounds.  Compare your audio system to a target curve of your choice quickly and easily.
  link: /docs/manual/plots.html

- title: Made for Tuning
  description: A portable audio analyzer made for tinkering with audio systems.  All you need is your iPhone or iPad.
  link: /TUNING.html

- title: Reliable
  description: Automatic validation ensures accurate sine sweep measurements of magnitude, phase and group delay.
  link: /docs/usage/measurement_process.html


- title: Room Correction
  description: Equalize your audio system in one step by generating filters for your parametric equalizer or convolution engine.
  link: /docs/tuning/equalization.html#automatic-equalization
  
- title: Subwoofer Phase
  description: Time align your subwoofer with confidence and enjoy fast and tight bass.
  link: /docs/tuning/time_align.html
  
- title: Crossover Selection
  description: Avoid the guesswork.  Measure how individual speakers perform and choose the right crossover frequency.
  link: /docs/tuning/crossover.html


- title: Connectivity
  description: Connect to your audio system with AirPlay, Bluetooth, headphone jack (analog) or just play the sweep file manually.
  link: /docs/usage/connection.html

- title: Microphones
  description: Achieve great results with just your iPhone or iPad.  Use external calibrated microphones for additional accuracy.
  link: /docs/usage/microphones.html

- title: Documentation
  description: Need help?  Follow step by step instructions on how to measure and tune your audio system.
  link: /HELP.html





